version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-beta{build}'
nuget:
  disable_publish_on_pr: true
build:
  verbosity: minimal
after_build:
- ps: nuget.exe pack .\PRI.Messaging.Primitives\PRI.Messaging.Primitives.csproj -Prop Configuration=Release -Symbols -version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: '*.nupkg'
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
