version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION

    dotnet pack -c Release  /p:Version=$env:APPVEYOR_BUILD_VERSION /p:PackageReleaseNotes="$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED" --include-symbols
artifacts:
- path: PRI.Messaging.Primitives\bin\Release\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: nuget
  on:
    branch: master